### ISSUE TITLE
browserless/chrome:1.35.0-chrome-stable crashes in the container

### ISSUE THREAD

**Issue by ekonwlo** [browserless/chrome#847]
**Describe the bug**
After updating the the docker image to browserless/chrome:1.35.0-chrome-stable it crashes the container after executing a job. With browserless/chrome:1.34.0-chrome-stable works fine.

**Output**
`Tue, 07 Jul 2020 20:50:07 GMT browserless:job WYC8YKQOFLS8HXB442L3J2D6GA8LVZUQ: Browser cleanup complete.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}`

**Some docker inspect info**
`  
          "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "APP_DIR=/usr/src/app",
                "CONNECTION_TIMEOUT=60000",
                "CHROME_PATH=/usr/bin/google-chrome",
                "HOST=0.0.0.0",
                "IS_DOCKER=true",
                "LANG=C.UTF-8",
                "NODE_ENV=production",
                "PORT=3000",
                "PUPPETEER_CHROMIUM_REVISION=756035",
                "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true",
                "USE_CHROME_STABLE=true",
                "WORKSPACE_DIR=/usr/src/app/workspace"
            ],
            "Cmd": [
                "./start.sh"
            ],
            "Image": "browserless/chrome:1.35.0-chrome-stable",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "browser": "HeadlessChrome/83.0.4103.97",
                "debuggerVersion": "326d148b9655369b86498d9ecca39f63dd2bdd2d",
                "protocolVersion": "1.3",
                "puppeteerVersion": "4.0.1",
                "v8Version": "8.3.110.9",
                "webkitVersion": "537.36 (@326d148b9655369b86498d9ecca39f63dd2bdd2d)"
            }
        },
`

**Additional context**
I have many browserless containers running under nginx load balancer (with recommended settings) on multiple 6CPUx16GB servers, so I wouldn't say it's a hardware issue. Also I use chrome just to open the page and take a screenshot of it, so the taks is not heavy.

**Comment by joelgriffith** [comment]
Yup, we’ve been noticing the same thing. Hopefully will have a fix soon, seems to be only isolated to chrome stable for now

**Comment by joelgriffith** [comment]
Should now be fixed in `1-chrome-stable`

**Comment by nigelellis** [comment]
@joelgriffith we're also hitting this same issue running on `1.36.0-puppeteer-5.0.0`.   I noticed you pushed a fix in https://github.com/browserless/chrome/pull/857 which is included in this build yet we still see the issue.   Is there another potential fix in the works or another release tag we should be using?   Thanks.

**Comment by arenstar** [comment]
Also getting this issue on browserless/chrome:1-chrome-stable ^^ 😒
